package com.smartboard.models;

import com.smartboard.Utils.DBManager;
import com.smartboard.controllers.ProjectController;
import com.smartboard.models.interfaces.Column;
import com.smartboard.models.interfaces.Project;

import java.util.ArrayList;
import java.util.List;

public class ProjectImpl implements Project {

    private final int id;
    private String name;
    private List<Column> columns;
    private WorkspaceImpl workSpace;
    private ProjectController controller;

    /**
     * Constructor to be used exvlusively by the DBManager when fetching and building
     * the user's workspace from the database.
     * using this constructor will not trigger a database insert
     *
     * @param name      the name of the project
     * @param workSpace the parent workspace of the project
     * @param id        the project's id
     */
    public ProjectImpl(String name, WorkspaceImpl workSpace, int id) {
        init(name, workSpace);
        this.id = id;
    }

    /**
     * creates a project object with database autogenerated id
     *
     * @param name      the name of the project
     * @param workSpace the parent workspace
     */
    public ProjectImpl(String name, WorkspaceImpl workSpace) {
        init(name, workSpace);
        this.id = DBManager.createProject(this);
    }

    /**
     * Helper internal constructor to avoid repetition
     *
     * @param name      the name of the project
     * @param workSpace the parent workspace
     */
    private void init(String name, WorkspaceImpl workSpace) {
        this.name = name;
        this.workSpace = workSpace;
        this.columns = new ArrayList<>();
    }

    @Override
    public void setController(ProjectController controller) {
        this.controller = controller;
    }

    @Override
    public ProjectController getController() {
        return controller;
    }

    @Override
    public int getId() {
        return id;
    }

    @Override
    public String getName() {
        return name;
    }

    /**
     * set method will trigger a DB update
     *
     * @param name the name of the project
     */
    @Override
    public void setName(String name) {
        this.name = name;
        update();
    }

    @Override
    public List<Column> getColumns() {
        return columns;
    }

    @Override
    public void setColumns(List<Column> columns) {
        this.columns = columns;
    }

    @Override
    public WorkspaceImpl getWorkSpace() {
        return workSpace;
    }

    /**
     * this setter will trigger a DB update
     *
     * @param workSpace the parent workspace
     */
    @Override
    public void setWorkSpace(WorkspaceImpl workSpace) {
        this.workSpace = workSpace;
        update();
    }

    @Override
    public List<Column> addColumn(Column column) {
        this.columns.add(column);
        return this.columns;
    }

    /**
     * deletes column from model and DB
     *
     * @param column The item to remove
     * @return the updated list of columns
     */
    @Override
    public List<Column> removeColumn(Column column) {
        this.columns.remove(column);
        column.delete();
        return this.columns;
    }


    @Override
    public boolean delete() {
        return DBManager.deleteProject(this);
    }

    @Override
    public boolean update() {
        return DBManager.updateProject(this);
    }
}